let RecipeCategories = {
    Cuisine: [
        "Africana",
        "Árabe",
        "Argentina",
        "Asiática",
        "Centroamericana",
        "Española",
        "Europea",
        "Fusión",
        "India",
        "Internacional",
        "Italiana",
        "Mediterránea",
        "Mexicana",
        "Peruana",
        "Sudamericana"
    ],
    Difficulty: [
        "Muy Fácil",
        "Fácil",
        "Media",
        "No Tan Fácil",
        "Difícil"
    ],
    IngredientCategories: [
        "Frutas y verduras",
        "Lácteos y quesos",
        "Carnes, aves y pescados",
        "Huevos",
        "Fiambres",
        "Pastas frescas y tapas",
        "Enlatados",
        "Encurtidos",
        "Aceites y condimentos",
        "Arroz y legumbres",
        "Pastas secas",
        "Dulces, conservas y frutos secos",
        "Panadería",
        "Harinas",
        "Bebidas",
    ],
    DishType: [
        "Guiso",
        "Pasta",
        "Ensalada",
        "Tarta",
        "Carne",
        "Pollo",
        "Pescado",
        "Cerdo",
        "Cordero",
        "Legumbres",
        "Arroz",
        "Sopa",
        "Pizza",
        "Vegetales",
        "Pan",
        "Pastel",
    ],
    Units: [
        "unidad",
        "gr.",
        "ml.",
        "kg.",
        "litro(s)",
        "cda(s)",
        "cdita(s)",
        "puñado",
        "rama(s)",
        "taza(s)"
    ]
}

export default RecipeCategories